---
- name: RHCSA EX200 - Storage Troubleshooting (Partitioning & Filesystems)
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Create mount points
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /mnt/data_ext4
        - /mnt/data_xfs

    - name: Create GPT partition on /dev/sdb
      parted:
        device: /dev/sdb
        number: 1
        label: gpt
        part_start: 1MiB
        part_end: 1GiB
        state: present

    - name: Create GPT partition on /dev/sde
      parted:
        device: /dev/sde
        number: 1
        label: gpt
        part_start: 1MiB
        part_end: 100%
        state: present

    - name: Create ext4 filesystem on /dev/sdb1
      filesystem:
        fstype: ext4
        dev: /dev/sdb1

    - name: Create xfs filesystem on /dev/sde1
      filesystem:
        fstype: xfs
        dev: /dev/sde1

    - name: Add entries to /etc/fstab (intentionally problematic)
      blockinfile:
        path: /etc/fstab
        block: |
          /dev/sdb1  /mnt/data_ext4  xfs   defaults  0 0
          /dev/sde1  /mnt/data_xfs   ext4  defaults  0 0

    - name: Attempt to mount filesystems
      command: mount -a
      ignore_errors: yes
