---
# /home/jensy/GitHub/Ansible/2_Storage_Redimensionar_LVs_y_sistemas_de_archivos.yml
---
- name: Configuración inicial para práctica de almacenamiento
  hosts: localhost
  become: true
  tasks:
    - name: Crear PV en /dev/sdb
      command: pvcreate /dev/sdb
      args:
        creates: /dev/sdb

    - name: Crear PV en /dev/sdc
      command: pvcreate /dev/sdc
      args:
        creates: /dev/sdc

    - name: Crear VG practicevg
      command: vgcreate practicevg /dev/sdb /dev/sdc
      args:
        creates: /dev/mapper/practicevg*

    - name: Crear LV datalv de 800M
      command: lvcreate -L 800M -n datalv practicevg

    - name: Formatear LV con XFS
      filesystem:
        fstype: xfs
        dev: /dev/practicevg/datalv

    - name: Crear punto de montaje
      file:
        path: /mnt/data
        state: directory

    - name: Montar LV
      mount:
        path: /mnt/data
        src: /dev/practicevg/datalv
        fstype: xfs
        state: mounted