---
- name: RHCSA EX200 - Storage Lab (LV Resize - Basic)
  hosts: rhcsa_vm
  become: true
  tasks:

    - name: Crear VG rhcsa_vg usando /dev/sdb
      lvg:
        vg: rhcsa_vg
        pvs: /dev/sdb

    - name: Crear LV data_lv de 800M
      lvol:
        vg: rhcsa_vg
        lv: data_lv
        size: 800M

    - name: Crear sistema de archivos XFS
      filesystem:
        fstype: xfs
        dev: /dev/rhcsa_vg/data_lv

    - name: Crear punto de montaje /data
      file:
        path: /data
        state: directory
        mode: '0755'

    - name: Montar /data
      mount:
        path: /data
        src: /dev/rhcsa_vg/data_lv
        fstype: xfs
        state: mounted

    - name: Crear archivo de prueba
      copy:
        dest: /data/info.txt
        content: "RHCSA storage lab initialized\n"
