
---
- name: RHCSA EX200 - Storage Lab | Resize LVs and Filesystems (BASIC)
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Ensure LVM tools are installed
      dnf:
        name:
          - lvm2
          - xfsprogs
        state: present

    - name: Create physical volume
      command: pvcreate /dev/sdb
      args:
        creates: /dev/sdb1
      ignore_errors: yes

    - name: Create volume group
      lvg:
        vg: vg_exam
        pvs: /dev/sdb

    - name: Create logical volume
      lvol:
        vg: vg_exam
        lv: lv_data
        size: 500M

    - name: Create XFS filesystem
      filesystem:
        fstype: xfs
        dev: /dev/vg_exam/lv_data

    - name: Create mount point
      file:
        path: /data
        state: directory
        mode: '0755'

    - name: Mount filesystem
      mount:
        path: /data
        src: /dev/vg_exam/lv_data
        fstype: xfs
        state: mounted

    - name: Persist mount in fstab
      mount:
        path: /data
        src: /dev/vg_exam/lv_data
        fstype: xfs
        opts: defaults
        state: present

    - name: Create sample data to consume space
      command: dd if=/dev/zero of=/data/dummyfile bs=1M count=300
      args:
        creates: /data/dummyfile
